version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: budgeting_app
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    restart: always

volumes:
  pgdata: